"""add is_registered to assoc table

Revision ID: 6830f901585d
Revises: ed72302a70a4
Create Date: 2022-09-10 22:16:49.780777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6830f901585d'
down_revision = 'ed72302a70a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_test_dates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_registered', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_test_dates', schema=None) as batch_op:
        batch_op.drop_column('is_registered')

    # ### end Alembic commands ###
