"""add score_date

Revision ID: ed72302a70a4
Revises: ffce279f0b0c
Create Date: 2022-09-08 21:33:52.455791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed72302a70a4'
down_revision = 'ffce279f0b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_date', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_date', schema=None) as batch_op:
        batch_op.drop_column('score_date')

    # ### end Alembic commands ###
