"""add other date

Revision ID: 78e69b704539
Revises: f1474540f0e4
Create Date: 2022-08-19 16:11:06.094753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e69b704539'
down_revision = 'f1474540f0e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_date', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_date', schema=None) as batch_op:
        batch_op.drop_column('other_date')

    # ### end Alembic commands ###
