"""rm fks

Revision ID: 090ad33010b7
Revises: 0bb68bfc8f9f
Create Date: 2022-09-28 16:55:33.377924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090ad33010b7'
down_revision = '0bb68bfc8f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_parent_id_user', 'user', ['parent_id'], ['id'])
        batch_op.create_foreign_key('fk_user_tutor_id_user', 'user', ['tutor_id'], ['id'])
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_tutor_id_user', type_='foreignkey')
        batch_op.drop_constraint('fk_user_parent_id_user', type_='foreignkey')
    # ### end Alembic commands ###
