"""user.session_reminders

Revision ID: 98e49c56e446
Revises: eb4cd35ec77c
Create Date: 2022-10-03 11:20:43.621960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e49c56e446'
down_revision = 'eb4cd35ec77c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_reminders', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('session_reminders')

    # ### end Alembic commands ###
