"""user.secondary_email

Revision ID: eb92c13b4c22
Revises: 424c302a9645
Create Date: 2022-09-29 15:56:01.600255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb92c13b4c22'
down_revision = '424c302a9645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_email', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('secondary_email')

    # ### end Alembic commands ###
