"""student_test_dates

Revision ID: ffce279f0b0c
Revises: 78e69b704539
Create Date: 2022-08-28 22:48:28.784767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffce279f0b0c'
down_revision = '78e69b704539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_test_dates',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('test_date_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['test_date_id'], ['test_date.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_test_dates')
    # ### end Alembic commands ###
