"""about_me and last_login to user

Revision ID: 3ab4dc3066ed
Revises: c3ae92c8fde7
Create Date: 2020-10-25 13:25:48.630290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab4dc3066ed'
down_revision = 'c3ae92c8fde7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
