"""field name from active to status

Revision ID: 4057880499ce
Revises: b03dee904163
Create Date: 2021-10-27 13:57:08.179347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4057880499ce'
down_revision = 'b03dee904163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=24), nullable=True))
        batch_op.create_index(batch_op.f('ix_student_status'), ['status'], unique=False)
        batch_op.drop_index('ix_student_active')
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.VARCHAR(length=24), nullable=True))
        batch_op.create_index('ix_student_active', ['active'], unique=False)
        batch_op.drop_index(batch_op.f('ix_student_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
