"""add date table

Revision ID: 4bb499ff41aa
Revises: 590907060c6a
Create Date: 2022-05-05 02:16:29.144840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb499ff41aa'
down_revision = '590907060c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('test', sa.String(length=24), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('reg_date', sa.Date(), nullable=True),
    sa.Column('late_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_date')
    # ### end Alembic commands ###
