"""resolve prod db tutor table

Revision ID: 590907060c6a
Revises: 4057880499ce
Create Date: 2022-03-14 07:16:03.786418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '590907060c6a'
down_revision = '4057880499ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('tutor',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('first_name', sa.String(length=64), nullable=True),
    #sa.Column('last_name', sa.String(length=64), nullable=True),
    #sa.Column('email', sa.String(length=64), nullable=True),
    #sa.Column('timezone', sa.Integer(), nullable=True),
    #sa.Column('status', sa.String(length=24), nullable=True),
    #sa.PrimaryKeyConstraint('id')
    #)
    #with op.batch_alter_table('tutor', schema=None) as batch_op:
    #    batch_op.create_index(batch_op.f('ix_tutor_email'), ['email'], unique=False)
    #    batch_op.create_index(batch_op.f('ix_tutor_first_name'), ['first_name'], unique=False)
    #    batch_op.create_index(batch_op.f('ix_tutor_status'), ['status'], unique=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('secondary_email', sa.String(length=64), nullable=True))
        #batch_op.alter_column('tutor_id',
        #       existing_type=mysql.INTEGER(display_width=11),
        #       nullable=True)
        #batch_op.create_index(batch_op.f('ix_student_tutor_id'), ['tutor_id'], unique=False)
        batch_op.create_foreign_key('fk_student_tutor_id_tutor', 'tutor', ['tutor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('tutor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('secondary_email')

    with op.batch_alter_table('tutor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tutor_status'))
        batch_op.drop_index(batch_op.f('ix_tutor_first_name'))
        batch_op.drop_index(batch_op.f('ix_tutor_email'))

    op.drop_table('tutor')
    # ### end Alembic commands ###
