"""secondary email

Revision ID: 7a4ba31031db
Revises: ebad7a91d4eb
Create Date: 2022-03-14 01:30:47.316413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4ba31031db'
down_revision = 'ebad7a91d4eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_email', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('secondary_email')

    # ### end Alembic commands ###
