"""add columns to student

Revision ID: 8a831235b59c
Revises: 61e7acad8c96
Create Date: 2021-08-06 13:31:33.095995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a831235b59c'
down_revision = '61e7acad8c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_name'))
        batch_op.add_column(sa.Column('student_email'))
        batch_op.add_column(sa.Column('parent_name'))
        batch_op.add_column(sa.Column('timezone'))
        batch_op.create_unique_constraint(batch_op.f('uq_student_student_name'), ['student_name'])
        batch_op.drop_column('tz')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('tz', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_student_student_name'), type_='unique')

    # ### end Alembic commands ###
