"""student status string

Revision ID: b03dee904163
Revises: c213b802d7d8
Create Date: 2021-10-27 13:54:15.900187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03dee904163'
down_revision = 'c213b802d7d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=24),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_student_student_name'), ['student_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_student_name'))
        batch_op.alter_column('active',
               existing_type=sa.String(length=24),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
