"""last name for students

Revision ID: c213b802d7d8
Revises: f4f8ed60c42f
Create Date: 2021-10-26 00:24:25.471875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c213b802d7d8'
down_revision = 'f4f8ed60c42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_student_student_name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.create_index(batch_op.f('ix_student_student_name'), ['student_name'], unique=True)

    # ### end Alembic commands ###
