"""student status

Revision ID: db92a4e4f808
Revises: 4780158ba4af
Create Date: 2021-09-16 22:03:36.472642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db92a4e4f808'
down_revision = '4780158ba4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_student_student_email'), ['student_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_student_name'), ['student_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_student_name'))
        batch_op.drop_index(batch_op.f('ix_student_student_email'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
