"""signup timestamp

Revision ID: ee4dcd109723
Revises: a5c47587f71e
Create Date: 2020-10-23 03:03:30.994634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4dcd109723'
down_revision = 'a5c47587f71e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_timestamp'), 'user', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_timestamp'), table_name='user')
    op.drop_column('user', 'timestamp')
    # ### end Alembic commands ###
