"""add pronouns

Revision ID: f4f8ed60c42f
Revises: 6b4a2a657760
Create Date: 2021-09-22 15:36:11.394910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f8ed60c42f'
down_revision = '6b4a2a657760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronouns', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('pronouns')

    # ### end Alembic commands ###
